apiVersion: v1
kind: Namespace
metadata:
  name: efklog
  labels:
    environment: production
    team: logging
  annotations:
    description: "Namespace for EFK (Elasticsearch, Fluentd, Kibana) logging stack"
