kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-es-config-v0.2.0
  namespace: efklog
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      log_level info  # Balanced verbosity for debugging.
      # Secure communication with TLS enabled for data in transit.
      <security>
        self_hostname "#{ENV['HOSTNAME']}"
        shared_key "YOUR_SHARED_KEY"
      </security>
    </system>

  # Enhanced containers log input configuration with optimized Fluentd plugins.
  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json  # Efficient JSON parsing.
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format regexp  # For non-JSON log parsing.
          expression /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Filters to modify, enrich log data and limit log processing.
    <filter **>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata  # Adding Kubernetes metadata.
      <kubernetes>
        # Ensuring secure communication with the Kubernetes API.
        use_ssl true
      </kubernetes>
    </filter>
    <filter **>
      @id filter_record_transformer
      @type record_transformer
      <record>
        hostname "#{Socket.gethostname}"
      </record>
      # Remove sensitive data from logs.
      remove_keys password, secret
    </filter>

    # Buffering configuration to manage bursts of log data efficiently.
    <buffer tag, time>
      @type memory
      total_limit_size 512MB
      chunk_limit_size 16MB
      flush_interval 5s
      retry_type exponential_backoff
      retry_forever true
      overflow_action block
    </buffer>

  # Fluentd output configuration optimized for Elasticsearch.
  output.conf: |-
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      host elasticsearch-logging
      port 9200
      scheme https  # Encrypting data in transit to Elasticsearch.
      ssl_verify false  # For demo purposes, in production, set to true.
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      type_name _doc
      include_tag_key true
      logstash_format true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        flush_thread_count 2
        flush_interval 5s
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
      <template>
        index_name fluentd-${record['kubernetes']['namespace_name']}-${Time.now.strftime('%Y%m%d')}
      </template>
    </match>
